/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.Unicolombo.pb.vista;

import co.edu.Unicolombo.pb.datos.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Garavito
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        itemIniciarSesionUsuarios = new javax.swing.JMenuItem();
        itemAgregarUsuarios = new javax.swing.JMenuItem();
        itemConsultarUsuarios = new javax.swing.JMenuItem();
        itemEditarUsuarios = new javax.swing.JMenuItem();
        itemEliminarUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        subMenuReporteUsuario = new javax.swing.JMenu();
        itemTodos = new javax.swing.JMenuItem();
        itemBuscarUsuarioXNombre = new javax.swing.JMenuItem();
        itemBuscarUsuarioXCodigo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("....GESTION DE USUARIO....");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/Unicolombo/pb/vista/iconos/user32px.png"))); // NOI18N
        menuUsuarios.setText("Usuarios");

        itemIniciarSesionUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemIniciarSesionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/Unicolombo/pb/vista/iconos/logout24px.png"))); // NOI18N
        itemIniciarSesionUsuarios.setText("Cerrar Sesion");
        itemIniciarSesionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIniciarSesionUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemIniciarSesionUsuarios);

        itemAgregarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAgregarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/Unicolombo/pb/vista/iconos/add24px.png"))); // NOI18N
        itemAgregarUsuarios.setText("Agregar Usuario");
        itemAgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemAgregarUsuarios);

        itemConsultarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemConsultarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/Unicolombo/pb/vista/iconos/find24px.png"))); // NOI18N
        itemConsultarUsuarios.setText("Consultar Usuario");
        itemConsultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemConsultarUsuarios);

        itemEditarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemEditarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/Unicolombo/pb/vista/iconos/edit24px.png"))); // NOI18N
        itemEditarUsuarios.setText("Editar Usuario");
        itemEditarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemEditarUsuarios);

        itemEliminarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemEliminarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/Unicolombo/pb/vista/iconos/delete24px.png"))); // NOI18N
        itemEliminarUsuarios.setText("Eliminar Usuario");
        itemEliminarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemEliminarUsuarios);
        menuUsuarios.add(jSeparator1);

        subMenuReporteUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/Unicolombo/pb/vista/iconos/control24px.png"))); // NOI18N
        subMenuReporteUsuario.setText("Control");

        itemTodos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemTodos.setText("Todos...");
        itemTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTodosActionPerformed(evt);
            }
        });
        subMenuReporteUsuario.add(itemTodos);

        itemBuscarUsuarioXNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemBuscarUsuarioXNombre.setText("Por Nombre");
        subMenuReporteUsuario.add(itemBuscarUsuarioXNombre);

        itemBuscarUsuarioXCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemBuscarUsuarioXCodigo.setText("Por codigo");
        subMenuReporteUsuario.add(itemBuscarUsuarioXCodigo);

        menuUsuarios.add(subMenuReporteUsuario);

        barraMenu.add(menuUsuarios);

        jMenu2.setText("Ayuda");

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem8.setText("Acerca de");
        jMenu2.add(jMenuItem8);

        barraMenu.add(jMenu2);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 938, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarUsuariosActionPerformed
        itemAgregarUsuariosActionPerformed(evt);
    }//GEN-LAST:event_itemConsultarUsuariosActionPerformed

    private void itemAgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarUsuariosActionPerformed
       VistaUsuarios v = new VistaUsuarios(this, true);
       v.setLocationRelativeTo(this);
       v.setVisible(true);
    }//GEN-LAST:event_itemAgregarUsuariosActionPerformed

    private void itemTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTodosActionPerformed
         if (Usuario.usuariosBD == null || Usuario.usuariosBD.isEmpty()){
            JOptionPane.showMessageDialog(this, "No existen Uusarios en el sistema"
            , "Resultado negativo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VistaReporteUsuarios v = new VistaReporteUsuarios(this, true);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemTodosActionPerformed

    private void itemEditarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarUsuariosActionPerformed
         itemAgregarUsuariosActionPerformed(evt);
    }//GEN-LAST:event_itemEditarUsuariosActionPerformed

    private void itemEliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarUsuariosActionPerformed
        itemAgregarUsuariosActionPerformed(evt);
    }//GEN-LAST:event_itemEliminarUsuariosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        VistaLogin v = new VistaLogin(this, true);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
        
    }//GEN-LAST:event_formWindowOpened

    private void itemIniciarSesionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIniciarSesionUsuariosActionPerformed
        formWindowOpened(null);
    }//GEN-LAST:event_itemIniciarSesionUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemAgregarUsuarios;
    private javax.swing.JMenuItem itemBuscarUsuarioXCodigo;
    private javax.swing.JMenuItem itemBuscarUsuarioXNombre;
    private javax.swing.JMenuItem itemConsultarUsuarios;
    private javax.swing.JMenuItem itemEditarUsuarios;
    private javax.swing.JMenuItem itemEliminarUsuarios;
    private javax.swing.JMenuItem itemIniciarSesionUsuarios;
    private javax.swing.JMenuItem itemTodos;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenu subMenuReporteUsuario;
    // End of variables declaration//GEN-END:variables
}
